version: "3.8"
services:
  elasticsearch:
    image: ghcr.io/hirotasoshu/movies-es:latest
    build:
      context: ./docker/es
      dockerfile: Dockerfile
      args:
        DISCOVERY_TYPE: single-node
    ports:
      - '9200:9200'
    volumes:
      - elasticdata:/usr/share/elasticsearch/data

  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - redisdata:/data
    ports:
      - '6379:6379'

  etl:
    image: ghcr.io/hirotasoshu/etl:latest
    restart: always
    build:
      context: .
      dockerfile: ./docker/etl/Dockerfile
    depends_on:
      - elasticsearch
      - redis
    env_file:
      - ./config/.env
    command: python main.py


volumes:
  elasticdata:
  redisdata:
